baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of codezengjie"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true


[menu]    
  [[menu.main]]
  name = "主页"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "文章"
  weight = 200
  identifier = "posts"
  url = "/english/post/"

  [[menu.main]]
  name = "关于"
  weight = 300
  identifier = "about"
  url = "/english/about"

# 需要重新建文件
# [[menu.footer]]
# name = "说明"
# weight = 1
# identifier = "imprint"
# url = "/english/imprint/"

  [[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 150
  pre = "internal"
  post = "tags"

# 头像设置
[params] 
profilePicture = "images/profile.jpg" 
favicon = "favicons/"

